#!name=Revenucat

#!desc=RevenueCat Universal hack

[URL Rewrite]
https:\/\/api\.revenuecat\.com\/v1\/subscribers\/(?!.*\/(offerings|attributes|adservices_attribution)$).* https://api.revenuecat.com/v1/product_entitlement_mapping header

[Script]
Revenucat=type=http-response,pattern=http-response https://api.revenuecat.com/v1/product_entitlement_mapping,requires-body=1,script-path=https://raw.githubusercontent.com/komo1iddin/surge-modules/main/scripts/RevenueCat-universal-hack.js

[MITM]
hostname= %APPEND% api.revenuecat.com



